Create block controller and routes
rowpacmal/bcu23d-nodejs-gruppuppgift-blockkedja pull request #17
Opened 2024-05-19 11:51 UTC by rowpacmal

Created the block controller and routes. Summary of what have been done in this branch:
- Created a new file in the controllers folder, named block-controller.mjs
- Created a new file in the routes folder, named block-routes.mjs
- Imported the router to the app.mjs file
- Added getBlockByIndex, getLatestBlock and createBlock functions in block-controlelrs.njs and exported them into block-routes.mjs

2024-05-19 16:18 UTC, alcompilor requested changes
Look for comments.
There is a conflict in `app.mjs` as well hope you can pull the latest version of `app.mjs` from `main` branch and fix the conflict in vscode.

2024-05-19 16:18 UTC, alcompilor commented on backend/controllers/block-controller.mjs
> +const blockchain = { chain: [Block.genesis] };
You can discard this when merging to production.

You can still "imagine" the presence of a `blockchain` variable that will be imported into the controller from another module, potentially from `app.mjs`.

2024-05-19 16:18 UTC, alcompilor commented on backend/controllers/block-controller.mjs
Wait to refactor so it uses the classes we made/planning to make for responses and errors.

2024-05-19 18:52 UTC, rowpacmal commented
I removed the test code and comments. I managed to merge the main into the branch and resolve the conflicts with no difficulties.

2024-05-19 20:03 UTC, rowpacmal commented
Replaced placeholder responses with ResponseData and ErrorResponse models.

2024-05-20 13:09 UTC, BTK88 approved these changes
# Dont notice any conflict or problem. Good Job!

2024-05-20 13:42 UTC, merged